name: Java CI with Maven

on:
  push:
    branches: [ "Int-Actions" ]
  pull_request:
    branches: [ "Int-Actions" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Build with Maven (Skip Tests)
        run: mvn -B clean package -DskipTests --file pom.xml

      - name: Test with Maven (Headless Mode)
        run: mvn -B test -Djava.awt.headless=true --file pom.xml

      - name: Generate Javadoc (Skip Tests)
        run: mvn -B javadoc:javadoc -DskipTests

      - name: Show Git Remote Configuration
        run: git remote -v

      - name: Configure Git for Deployment
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site/apidocs
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true

    env:
      ACTIONS_RUNNER_DEBUG: true
